name: Testing # This is the name of the workflow
on:
  push: # Triggers the workflow on push events to the repository
    branches:
      - main # Set the branch you want to deploy from
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab

jobs:
  test: # This is the ID of the job
    runs-on: ubuntu-latest # Specifies the type of runner to use. The available runners are hosted by GitHub
    steps: # This section defines the steps that will be executed as part of the job
      - name: Get code
        uses: actions/checkout@v4 # Use the latest version of checkout action
      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Print node version
        run: node -v
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
  deploy:
    needs: test # This job will only run if the 'test' job completes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Deployment step
        run: echo "Deploying application..." # Replace this with your actual deployment commands
      - name: Build project
        run: npm run build
